### ISSUE TITLE
Source file 'Aspose.Slides-for-.NET\Examples\CSharp\Charts\SetExternalWorkbookFromNetwork.cs' could not be found.

### ISSUE THREAD

**Issue by PapaMufflon** [aspose-slides/Aspose.Slides-for-.NET#32]
There is a missing file that prevents the project to build.

**Comment by mannanfazil** [comment]
@PapaMufflon 
Please download the latest project. All examples are getting compiled successfully now and you may please verify them. If still there is any issue, please feel free to share with us.

**Comment by PapaMufflon** [comment]
Great, it's getting close. Only problem is that there are 3 files referenced in obj folder:

```
<Compile Include="obj\x86\Debug\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs" />
<Compile Include="obj\x86\Debug\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs" />
<Compile Include="obj\x86\Debug\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs" />
```

I guess those can be deleted from the project file.

**Comment by mannanfazil** [comment]
@PapaMufflon 
I have removed these references from the project. Please download the latest project file. Thanks

**Comment by PapaMufflon** [comment]
👍 Build succeeded!
